### ISSUE TITLE
Select a font only for monospace (codeblock, frontmatter)

### ISSUE THREAD

**Issue by BenRoe** [pourmand1376/obsidian-custom-font#13]
In the Obsidian appearance settings i can select a font only codeblocks and frontmatter.
Is it possible with this plugin?

**Comment by pourmand1376** [comment]
Hi. 

Yes. It is possible. I believe what you want is these three settings in obsidian:
![CleanShot 2024-04-30 at 00 09 23@2x](https://github.com/pourmand1376/obsidian-custom-font/assets/32064808/078219d7-10de-4750-abec-6b0957422b33)

Also, In the plugin if you enable custom css mode, if you enable `custom css mode`, you will see something like this:

```
:root * {
		--font-default: Shabnam;
		--default-font: Shabnam;
		--font-family-editor: Shabnam;
		--font-monospace-default: Shabnam,
		--font-interface-override: Shabnam,
		--font-text-override: Shabnam,
		--font-monospace-override: Shabnam,	
	}

```
Here you can customize the css however you want. For example, if you want the font to only be applied as a monospace font and not applied any where else:
```
:root * {
		--font-monospace-default: Shabnam,
		--font-monospace-override: Shabnam,	
	}

```

And I think it is clear where I am going by this. 

Feel free to change and tweak other css settings to see what each mean.

**Comment by BenRoe** [comment]
Thank you. Via standard settings, my font (Fira Code) is not in the list.
If i use the following css, Fira Code font is used. Only problem is, ligatures are not active. Any idea how to do it?
```css
:root * {
		--font-default: none;
		--default-font: none;
		--font-family-editor: none;
		--font-monospace-default: "Fira Code",
		--font-interface-override: none,
		--font-text-override: none,
		--font-monospace-override: "none",
                -webkit-font-feature-settings: "liga" on, "calt" on;
	}
```
