### ISSUE TITLE
Would love to set font only for tasks

### ISSUE THREAD

**Issue by lenalebt** [pourmand1376/obsidian-custom-font#3]
Hey,
wow, thanks for the plugin :smile: ! I just recently created a font of my handwriting and would LOVE to use it on Obsidian. For the whole thing it's a bit too much, but I would love to use it for ticking off tasks. If I could somehow (using CSS rules?) to apply the font only there, it would be rad. Do you know if there is a way to achieve it?

Cheers,
Lena

**Comment by pourmand1376** [comment]
Hi, 
This feature is now added to the plugin. Please test it and provide feedback! 

![image](https://github.com/pourmand1376/obsidian-custom-font/assets/32064808/4ebbbd92-99ae-43fc-9613-5759042aebdc)

**Comment by lenalebt** [comment]
Hey wow, thanks for implementing this!
How exactly did you imagine using it? I used this snippet to get it to work now:

```css
.task-list-item {
    font-family: 'HandschriftLena-Regular', sans-serif;
    font-size: 24px;
}
.HyperMD-task-line {
    font-family: 'HandschriftLena-Regular', sans-serif;
    font-size: 24px;
}
```

It also worked as a "custom css snippet" with the default obsidian feature, but I am unsure whether I needed some of your recent changes for this to work or not?

Cheers,
Lena

**Comment by pourmand1376** [comment]
You need to use the newest version since by default it overrides all theme fonts. 

This is what It does in default settings:
```css
:root {
		--font-default: Shabnam;
		--default-font: Shabnam;
		--font-family-editor: Shabnam;
		--font-monospace-default: Shabnam,
		--font-interface-override: Shabnam,
		--font-text-override: Shabnam,
		--font-monospace-override: Shabnam,	
	}
```
