### ISSUE TITLE
not apply font to math

### ISSUE THREAD

**Issue by LukasLow** [pourmand1376/obsidian-custom-font#5]
hello maybe i am wrong but if i leave :root empty it still applies the font. I guess i can't remove the font from parts of it. My goal is to not apply a font to math and code because of this 

<img width="165" alt="image" src="https://github.com/pourmand1376/obsidian-custom-font/assets/99747166/cdf8b282-a41a-4879-837d-238bae9ab1c4">
 instead of a regular one 
<img width="170" alt="image" src="https://github.com/pourmand1376/obsidian-custom-font/assets/99747166/c194701b-ddc6-4b71-8c66-af17298d1f60">

**Comment by pourmand1376** [comment]
I've tested this now and If I leave :root like this, it would do nothing. 
```css
:root {

	}
```
However, you should find the appropriate CSS to apply. Maybe removing these CSS attributes one by one can help.

```css
:root {
		--font-default: Shabnam;
		--default-font: Shabnam;
		--font-family-editor: Shabnam;
		--font-monospace-default: Shabnam,
		--font-interface-override: Shabnam,
		--font-text-override: Shabnam,
		--font-monospace-override: Shabnam,	
	}
```
